name: Fundpad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cached_network_image: 2.0.0-rc
  cloud_firestore: ^0.14.3
  firebase_core : ^0.5.0
  firebase_storage: ^5.0.1
  firebase_auth:
  firebase_messaging:
  toast: ^0.1.5
  url_launcher:
  intl: ^0.16.1
  image_picker: ^0.6.7+14
  path_provider: ^1.6.24
  path: ^1.7.0
  uuid: ^2.2.2
  qrscan: ^0.2.17
  flutter_datetime_picker: ^1.4.0
  carousel_pro:
  flutter_masked_text:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - assets/placeholders/
    - assets/buttons/
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
